### ISSUE TITLE
iOS: Undefined symbols for architecture x86_64 in v0.14.0

### ISSUE THREAD

**Issue by heracek** [getsentry/react-native-sentry#126]
Sentry v0.14.0 does not build on iOS Simulator. Is it possible to distribute this library with simulator support?

Build error is:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSentry", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
```

---
Update:

It seems that problem is that `libRNSentry.a` was not added **Linked Frameworks and Libraries**.

**Comment by HazAT** [comment]
Have you called `react-native link react-native-sentry` ?

**Comment by doochik** [comment]
I have the same problem with 0.14.5 after `react-native link react-native-sentry`
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BugsnagReactNative", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_KSCrash", referenced from:
      objc-class-ref in libRNSentry.a(SentryContext.o)
      objc-class-ref in libRNSentry.a(SentryClient.o)
  "_OBJC_CLASS_$_KSCrashInstallation", referenced from:
      _OBJC_CLASS_$_SentryKSCrashInstallation in libRNSentry.a(SentryKSCrashInstallation.o)
  "_OBJC_METACLASS_$_KSCrashInstallation", referenced from:
      _OBJC_METACLASS_$_SentryKSCrashInstallation in libRNSentry.a(SentryKSCrashInstallation.o)
ld: symbol(s) not found for architecture x86_64
```

XCode 8.3.3, RN 0.46.1

**Comment by hogggy** [comment]
I've had the same issue after upgrading to v0.14.5, unlinking and linking react-native-sentry did not solve the problem

XCode 8.3.3, RN 0.46.2

**Comment by HazAT** [comment]
I think there is currently a bug in react-native with the link step.
Can you try patching this file locally in you `node_modules` folder and see if link works?
https://github.com/facebook/react-native/pull/14863

**Comment by HazAT** [comment]
I am closing this issue for now since I am pretty confident that it is a linking issue.
It seems react-native also resolved their issue.
If you are still having trouble, feel free to comment again.

**Comment by CoreyAR** [comment]
I am having this problem. The app builds but produces this failure. Can you explain what you mean by "patching the file locally in your node_modules"?

**Comment by HazAT** [comment]
@CoreyAR Hey, can you zip up your project folder and send it to me via email daniel@sentry.io
I am really eager to reproduce this issue but never encountered it, I really need to have the exact same env.

**Comment by wellyshen** [comment]
This issue occurs again.

react-native-sentry: v0.35.3
react-native: v0.54.2
xCode: 9.2

**Comment by LironErman** [comment]
Make sure u added "RNSentry.xcodeproj" to Libraries And libRNSentry.a to "Linked Frameworks and Libraries", that fixed the issue for me

**Comment by rewieer** [comment]
I had the same issue. I saw that the Wizard put the Sentry dependency on the TvOS tests. I've put it out, cleared and reinstalled my Pods, and it worked !
