### ISSUE TITLE
[android] cannot compile react-native-sentry@0.40.1

### ISSUE THREAD

**Issue by gianpaj** [getsentry/react-native-sentry#511]
OS:
- [x]  MacOS

_Platform:_
- [x]  Android

<details>
  <summary>Output of node -v && npm -v && npm ls --prod --depth=0</summary>
  <p>

```
v10.13.0
6.4.1
onova@0.0.1 /Users/gianfranco/temp/dec03
├── @pusher/chatkit@0.7.18
├── antd-mobile-rn@2.3.1
├── axios@0.18.0
├── babel-plugin-transform-remove-console@6.9.4
├── bson-objectid@1.2.4
├── date-fns@1.29.0
├── foect@0.1.5
├── google-libphonenumber@3.2.1
├── immutability-helper@2.8.1
├── intl@1.2.5
├── invariant@2.2.4
├── native-base@2.8.1
├── react@16.6.1
├── react-native@0.57.7
├── react-native-elements@0.19.1
├── react-native-firebase@5.1.1
├── react-native-i18n@2.0.15
├── react-native-sentry@0.39.1
├── react-navigation@3.0.5
├── react-navigation-redux-helpers@2.0.8
├── react-redux@5.1.1
├── redux-persist@5.10.0
├── redux-thunk@2.3.0
└── validator@10.9.0
```
</p></details>

<details>
  <summary>react-native info</summary>
  <p>

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 37.71 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 20.0.0, 21.1.2, 22.0.1, 23.0.3, 25.0.3, 26.0.2, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-rename: 2.4.0
```

</p></details>

---
I have the following issue:

cannot compile Android RN build

**Steps to reproduce:**
```
react-native run-android
```

**Actual result:**
```
> Task :react-native-sentry:compileDebugJavaWithJavac FAILED
/Users/gianfranco/temp/dec03/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:247: error: cannot find symbol
            ReadableArray fingerprint = event.getArray("fingerprint");
            ^
  symbol:   class ReadableArray
  location: class RNSentryModule
/Users/gianfranco/temp/dec03/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:248: error: cannot find symbol
            ArrayList<String> print = new ArrayList<String>(fingerprint.size());
            ^
  symbol:   class ArrayList
  location: class RNSentryModule
/Users/gianfranco/temp/dec03/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:248: error: cannot find symbol
            ArrayList<String> print = new ArrayList<String>(fingerprint.size());
                                          ^
  symbol:   class ArrayList
  location: class RNSentryModule
Note: /Users/gianfranco/temp/dec03/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```

<details>
  <summary>FYI: I'm using Grade 4.6</summary>
  <p>

`gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

`/android/build.gradle`
```
task wrapper(type: Wrapper) {
    gradleVersion = '4.6'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```
</details>

----

Downgrading to `v0.39.1` works:
```
yarn add react-native-sentry@v0.39.1
```

**Comment by HazAT** [comment]
Sorry, will check whats going on.

**Comment by HazAT** [comment]
`0.40.2` is on its way, sorry for any this may have caused inconvenience.

**Comment by gianpaj** [comment]
thanks for the quick fix @HazAT.

I can confirm it compiles now 👍🙂

**Comment by mxmzb** [comment]
I'm having this again on `0.41.1`

**Comment by mutablestudio** [comment]
I'm also seeing the error `...RNSentryModule.java uses or overrides a deprecated API.` when building a release build on Android Studio 3.3.1. Project is Expo detached  w react-native-sentry `0.42.0`. 

rolling back to `0.40.2` fixes it.
